// it's autogenerated. Don't edit it manually!
import { RequestLang, ResponseLang } from "@vot.js/shared/types/data";
import { SubtitleFormat } from "@vot.js/shared/types/subs";

export type Schema = {
  preview: boolean;
  "subs-format": SubtitleFormat;
  subs: boolean;
  subtitles: boolean;
  version: boolean;
  help: boolean;
  proxy: string;
  "worker-host": string;
  "vot-host": string;
  reslang: ResponseLang;
  lang: RequestLang;
  "old-model": boolean;
  "no-visual": boolean;
  outfile: string;
  out: string;
  outdir: string;
};
