// it's autogenerated. Don't edit it manually!
import type { RequestLang, ResponseLang } from "@vot.js/shared/types/data";
import type { SubtitleFormat } from "@vot.js/shared/types/subs";

export type Schema = {
  preview: boolean;
  "subs-format": SubtitleFormat;
  subs: boolean;
  subtitles: boolean;
  version: boolean;
  help: boolean;
  proxy: string;
  "worker-host": string;
  "vot-host": string;
  reslang: ResponseLang;
  lang: RequestLang;
  "lively-voice": boolean;
  "no-visual": boolean;
  json: boolean;
  outfile: string;
  out: string;
  outdir: string;
  "api-token": string;
};
