import path from "node:path";

import { schema } from "../src/resources/schema";

async function generateSchemaType() {
  const schemaTypeItems = Object.entries(schema).map(([key, value]) => {
    const itemName = key.includes("-") ? `"${key}"` : key;

    return `${itemName}: ${value.validator && value.validatorType ? value.validatorType : value.type};`;
  });

  await Bun.write(
    path.join(__dirname, "..", "src", "types", "schema.ts"),
    `// it's autogenerated. Don't edit it manually!
import { RequestLang, ResponseLang } from "@vot.js/shared/types/data";
import { SubtitleFormat } from "@vot.js/shared/types/subs";

export type Schema = {
  ${schemaTypeItems.join("\n  ")}
}`,
  );
}

await generateSchemaType();
