import path from "node:path";
import * as prettier from "prettier";

import { schema } from "../src/resources/schema";

async function generateSchemaType() {
  const schemaTypeItems = Object.entries(schema).map(([key, value]) => {
    const itemName = key.includes("-") ? `"${key}"` : key;

    return `${itemName}: ${value.validator && value.validatorType ? value.validatorType : value.type};`;
  });

  const rawCode = `// it's autogenerated. Don't edit it manually!
import { RequestLang, ResponseLang } from "@vot.js/shared/types/data";
import { SubtitleFormat } from "@vot.js/shared/types/subs";

export type Schema = {
  ${schemaTypeItems.join("\n  ")}
}`;
  const schemaPath = path.join(__dirname, "..", "src", "types", "schema.ts");
  const code = await prettier.format(rawCode, {
    filepath: schemaPath,
  });

  await Bun.write(schemaPath, code);
}

await generateSchemaType();
