import path from "node:path";
import { format } from "oxfmt";

import { schema } from "../src/resources/schema";

async function generateSchemaType() {
  const schemaTypeItems = Object.entries(schema).map(([key, value]) => {
    const itemName = key.includes("-") ? `"${key}"` : key;

    return `${itemName}: ${value.validator && value.validatorType ? value.validatorType : value.type};`;
  });

  const rawCode = `// it's autogenerated. Don't edit it manually!
import type { RequestLang, ResponseLang } from "@vot.js/shared/types/data";
import type { SubtitleFormat } from "@vot.js/shared/types/subs";

export type Schema = {
  ${schemaTypeItems.join("\n  ")}
}`;
  const schemaPath = path.join(__dirname, "..", "src", "types", "schema.ts");
  const result = await format(schemaPath, rawCode);

  await Bun.write(schemaPath, result.code);
}

await generateSchemaType();
